version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Colombo
    volumes:
      - ./appdata/nextcloud/config:/config
      - ./appdata/nextcloud/data:/data
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped 
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Colombo
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./appdata/mariadb:/config
    restart: unless-stopped
  online:
    image: libreoffice/online:master
    environment:
      domain: ${NEXTCLOUD_DOMAIN}
      username: ${LO_ONLINE_USERNAME}
      password: ${LO_ONLINE_PASSWORD}
      extra_params: ${LO_ONLINE_EXTRA_PARAMS}
      DONT_GEN_SSL_CERT: 1
    volumes:
      - ./appdata/online:/config
    cap_add:
      - MKNOD
    restart:
      unless-stopped
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Colombo
      - URL=wnl.lk
      - SUBDOMAINS=wnldrive,
      - VALIDATION=http
      - EMAIL=dasun@wnl.lk #optional
      - ONLY_SUBDOMAINS=true #optional
    volumes:
      - ./appdata/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
